- name: Get current node info
  community.general.docker_node_info:
    self: yes
  register: swarm_node_info

- name: Add label to node
  community.general.docker_node:
    # Here we grab the id of the current node, since all the nodes have
    # the same hostname at the moment (TODO: Consider changing that?)
    hostname: "{{ swarm_node_info['nodes'][0]['ID'] }}"
    labels:
      swarmpit.db-data: "true"
      swarmpit.influx-data: "true"

- name: Install swarmpit stack yml
  template:
    src: swarmpit.yml.j2
    dest: /root/swarmpit.yml
    mode: '0440'

- name: Deploy swarmpit stack
  community.general.docker_stack:
    state: present
    name: swarmpit
    compose:
      - /root/swarmpit.yml
  environment:
    DOMAIN: swarmpit.{{ domain }}