version: "3.8"

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=UTC"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      restart_policy: 
        condition: any
      placement:
        constraints:
          - node.role == manager